version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - shared-proxy

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        restart: on-failure
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.teapot.rule=Host(`teapot.418.ovh`)"
                - "traefik.docker.network=shared-proxy"
                - "traefik.http.routers.teapot.tls=true"
                - "traefik.http.routers.teapot.tls.certresolver=mytlschallenge"
                - "traefik.http.services.teapot.loadbalancer.server.port=80"
        networks:
            - shared-proxy

volumes:
    db_data: {}

networks:
    shared-proxy:
        external: true
